name: Setup
description: Setup environment for building and deploying the project
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    # Restore pnpm cache only (pnpm manages Node.js version independently)
    - name: Restore pnpm cache
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        cache: pnpm

    - name: Install dependencies
      run: pnpm install
      shell: bash
