allowBuilds:
  "@iorate/wepub": true
  esbuild: true
  lefthook: true

blockExoticSubdeps: true

minimumReleaseAge: 1440 # 1 day

trustPolicy: no-downgrade

virtualStoreDirMaxLength: 120 # pin for AMO reproducible builds
