allowBuilds:
  esbuild: true
  lefthook: true

blockExoticSubdeps: true

minimumReleaseAge: 4320 # 3 days

minimumReleaseAgeExclude:
  - "@ublacklist/*"

trustPolicy: no-downgrade

virtualStoreDirMaxLength: 120 # pin for AMO reproducible builds
