import fs from "node:fs/promises";

import { dump } from "js-yaml";

import { type Language, languages } from "./languages.ts";

function toCrowdinConfig(languages: readonly Language[]): string {
  const config = {
    project_id_env: "CROWDIN_PROJECT_ID",
    api_token_env: "CROWDIN_PERSONAL_TOKEN",
    preserve_hierarchy: true,
    files: [
      {
        source: "/src/_locales/en/messages.json",
        translation: "/src/_locales/%two_letters_code%/messages.json",
        dest: "/messages.json",
        languages_mapping: {
          two_letters_code: Object.fromEntries(
            languages.map(({ crowdin, browser }) => [crowdin, browser]),
          ),
        },
      },
      {
        source: "/README.md",
        translation: "/README.%two_letters_code%.md",
        dest: "/README.md",
        languages_mapping: {
          two_letters_code: Object.fromEntries(
            languages.map(({ crowdin, readme }) => [
              crowdin,
              readme ?? crowdin,
            ]),
          ),
        },
      },
    ],
  };
  return `# Generated by scripts/generate-languages.ts from languages.yml. Do not edit directly.
${dump(config)}`;
}

function toCrowdinGitExclude(languages: readonly Language[]): string {
  return [
    "# Generated by scripts/generate-languages.ts from languages.yml. Do not edit directly.",
    "README.*.md",
    ...languages
      .filter(({ readme }) => readme != null)
      .map(({ readme }) => `!README.${readme}.md`),
    "",
  ].join("\n");
}

function toWebsiteLocalesModule(languages: readonly Language[]): string {
  const websiteLocales = Object.fromEntries(
    languages
      .filter(({ website }) => website != null)
      .map(({ browser, website }) => [browser, website]),
  );
  return `export const websiteLocales: Readonly<Record<string, string>> = ${JSON.stringify(websiteLocales, null, 2)};
`;
}

async function main() {
  await fs.writeFile("crowdin.yml", toCrowdinConfig(languages));
  await fs.writeFile(
    ".github/crowdin-git-exclude",
    toCrowdinGitExclude(languages),
  );
  await fs.writeFile(
    "src/scripts/shared/website-locales.generated.ts",
    toWebsiteLocalesModule(languages),
  );
}

await main();
