import fs from "node:fs/promises";

import { dump, load } from "js-yaml";
import * as z from "zod";

const languageSchema = z.object({
  browser: z.string(),
  crowdin: z.string(),
  readme: z.string().optional(),
  website: z.string().optional(),
});

const languagesSchema = languageSchema.array();

type Language = z.infer<typeof languageSchema>;

function toCrowdinConfig(languages: readonly Language[]): string {
  const config = {
    project_id_env: "CROWDIN_PROJECT_ID",
    api_token_env: "CROWDIN_PERSONAL_TOKEN",
    preserve_hierarchy: true,
    files: [
      {
        source: "/src/_locales/en/messages.json",
        translation: "/src/_locales/%two_letters_code%/messages.json",
        dest: "/messages.json",
        languages_mapping: {
          two_letters_code: Object.fromEntries(
            languages.map(({ crowdin, browser }) => [crowdin, browser]),
          ),
        },
      },
      {
        source: "/README.md",
        translation: "/README.%two_letters_code%.md",
        dest: "/README.md",
        excluded_target_languages: languages
          .filter(({ readme }) => readme == null)
          .map(({ crowdin }) => crowdin),
        languages_mapping: {
          two_letters_code: Object.fromEntries(
            languages
              .filter(({ readme }) => readme != null)
              .map(({ crowdin, readme }) => [crowdin, readme]),
          ),
        },
      },
    ],
  };
  return `# Generated by scripts/generate-languages.ts from languages.yml. Do not edit directly.
${dump(config)}`;
}

function toWebsiteLocalesModule(languages: readonly Language[]): string {
  const websiteLocales = Object.fromEntries(
    languages
      .filter(({ website }) => website != null)
      .map(({ browser, website }) => [browser, website]),
  );
  return `export const websiteLocales: Readonly<Record<string, string>> = ${JSON.stringify(websiteLocales, null, 2)};
`;
}

async function main() {
  const languages = languagesSchema.parse(
    load(await fs.readFile("languages.yml", { encoding: "utf-8" })),
  );
  await fs.writeFile("crowdin.yml", toCrowdinConfig(languages));
  await fs.writeFile(
    "src/scripts/shared/website-locales.generated.ts",
    toWebsiteLocalesModule(languages),
  );
}

await main();
