import fs from "node:fs/promises";

import { dump } from "js-yaml";

import { type Language, languages } from "./languages.ts";

const header =
  "# Generated by scripts/generate-languages.ts from languages.yml. Do not edit directly.";

function toCrowdinConfig(languages: readonly Language[]): string {
  const config = {
    project_id_env: "CROWDIN_PROJECT_ID",
    api_token_env: "CROWDIN_PERSONAL_TOKEN",
    preserve_hierarchy: true,
    files: [
      {
        source: "/src/_locales/en/messages.json",
        translation: "/src/_locales/%two_letters_code%/messages.json",
        dest: "/messages.json",
        languages_mapping: {
          two_letters_code: Object.fromEntries(
            languages.map(({ crowdin, directory }) => [crowdin, directory]),
          ),
        },
      },
      {
        source: "/README.md",
        translation: "/README.%two_letters_code%.md",
        dest: "/README.md",
        languages_mapping: {
          two_letters_code: Object.fromEntries(
            languages.map(({ crowdin, tag }) => [crowdin, tag]),
          ),
        },
      },
    ],
  };
  return `${header}\n${dump(config)}`;
}

function toCrowdinGitExclude(languages: readonly Language[]): string {
  return [
    header,
    "README.*.md",
    ...languages
      .filter(({ readme }) => readme)
      .map(({ tag }) => `!README.${tag}.md`),
    "",
  ].join("\n");
}

function toLocalesModule(languages: readonly Language[]): string {
  const locales = Object.fromEntries(
    languages.map(({ tag, dayjs, website }) => [tag, { dayjs, website }]),
  );
  return `export const locales: Readonly<
  Record<string, { dayjs: string; website: boolean }>
> = ${JSON.stringify(locales, null, 2)};
`;
}

function toDayjsLocalesModule(languages: readonly Language[]): string {
  return [
    ...languages.map(({ dayjs }) => `import "dayjs/locale/${dayjs}";`),
    "",
  ].join("\n");
}

async function main() {
  await fs.writeFile("crowdin.yml", toCrowdinConfig(languages));
  await fs.writeFile(
    ".github/crowdin-git-exclude",
    toCrowdinGitExclude(languages),
  );
  await fs.writeFile(
    "src/scripts/shared/locales.generated.ts",
    toLocalesModule(languages),
  );
  await fs.writeFile(
    "src/scripts/shared/dayjs-locales.generated.ts",
    toDayjsLocalesModule(languages),
  );
}

await main();
