name: Build website

on:
  pull_request:
    branches:
      - master
    paths:
      - website/**
      - '!website/README.md'
  workflow_dispatch:

jobs:
  build:
    name: Build website

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache .yarn/cache
        uses: actions/cache@v3
        env:
          cache-name: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: yarn install --immutable

      - name: Lint
        run: yarn lint
        working-directory: website

      - name: Build website
        run: yarn build
        working-directory: website
