name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          run_install: true
          cache: true

      - name: pnpm biome ci
        run: pnpm biome ci --reporter=github

      - name: pnpm prettier
        run: pnpm prettier --check '**/*.{md,yaml,yml}'

      - name: pnpm tsgo
        run: pnpm tsgo

      - name: pnpm test
        run: pnpm test

      - name: pnpm build
        run: |
          pnpm build
          pnpm build --browser edge
          pnpm build --browser firefox
          pnpm build --browser safari
        env:
          DROPBOX_API_KEY: ${{ secrets.DROPBOX_API_KEY }}
          DROPBOX_API_SECRET: ${{ secrets.DROPBOX_API_SECRET }}
          GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          GOOGLE_DRIVE_API_SECRET: ${{ secrets.GOOGLE_DRIVE_API_SECRET }}

  actionlint:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: docker://rhysd/actionlint:1.7.12@sha256:9d36088643581e728c969f35141f88139fec77280b2be23c1f66f8e40e1025e7
        with:
          args: -color

  zizmor:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
