name: Crowdin

on:
  push:
    branches:
      - master
    paths:
      - src/_locales/en/messages.json
      - README.md
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  crowdin:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Generate token for pull request
        id: generate-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ vars.PULL_REQUESTS_CLIENT_ID }}
          private-key: ${{ secrets.PULL_REQUESTS_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Run crowdin
        uses: crowdin/github-action@8868a33591d21088edfc398968173a3b98d51706 # v2.16.2
        with:
          download_translations: true
          export_only_approved: true
          download_translations_args: --ignore-match
          pull_request_base_branch_name: master
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
