name: Crowdin

on:
  push:
    branches:
      - master
    paths:
      - src/_locales/en/messages.json
      - README.md
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}

defaults:
  run:
    shell: bash

jobs:
  crowdin:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Generate token for pull request
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.PULL_REQUESTS_CLIENT_ID }}
          private-key: ${{ secrets.PULL_REQUESTS_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Run crowdin
        uses: crowdin/github-action@52aa776766211d83d975df51f3b9c53c2f8ba35f # v2.16.3
        with:
          download_translations: true
          export_only_approved: true
          download_translations_args: --ignore-match
          pull_request_base_branch_name: master
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
