name: deploy (website)

permissions:
  contents: read
  id-token: write
  pages: write

on:
  push:
    branches:
      - master
    paths:
      - website/**

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
        working-directory: website
      - uses: actions/upload-pages-artifact@v3
        with:
          path: website/build
  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
