name: Release to web stores

on: workflow_dispatch

jobs:
  release:
    name: Release to web stores

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: yarn install --immutable

      - name: Build extension
        run: yarn run-p -l "build chrome production" "build firefox production"
        env:
          DROPBOX_API_KEY: ${{ secrets.DROPBOX_API_KEY }}
          DROPBOX_API_SECRET: ${{ secrets.DROPBOX_API_SECRET }}
          GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          GOOGLE_DRIVE_API_SECRET: ${{ secrets.GOOGLE_DRIVE_API_SECRET }}

      - name: Release to web stores
        run: yarn semantic-release
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          FIREFOX_API_KEY: ${{ secrets.FIREFOX_API_KEY }}
          FIREFOX_SECRET_KEY: ${{ secrets.FIREFOX_SECRET_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
