name: Renovate

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}

jobs:
  renovate:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          # https://docs.renovatebot.com/modules/platform/github/#running-as-a-github-app
          permission-checks: write
          permission-statuses: write
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
          permission-workflows: write
          permission-administration: read
          permission-vulnerability-alerts: read
          permission-metadata: read

      - name: Run Renovate
        uses: renovatebot/github-action@b50d2ba2bd928235abdcc14d06dfafc217f1c565 # v46.1.18
        with:
          token: ${{ steps.generate-token.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
