name: Update submodules

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: recursive

      - name: git submodule update
        run: git submodule update --remote

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Create pull request
        id: create-pull-request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update submodules
          branch: update-submodules
          sign-commits: true
          title: Update submodules

      - name: Enable auto-merge
        if: ${{ steps.create-pull-request.outputs.pull-request-number }}
        run: gh pr merge --squash --auto "$PULL_REQUEST_NUMBER"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          PULL_REQUEST_NUMBER: ${{ steps.create-pull-request.outputs.pull-request-number }}
