target 'uBlacklist for Safari (iOS)' do
  platform :ios, '15.0'
  use_frameworks!

  # Pods for uBlacklist for Safari (iOS)
  pod 'SnapKit', '~> 5.0.0'
end

target 'uBlacklist for Safari (macOS)' do
  platform :osx, '10.14'
  use_frameworks!

  # Pods for uBlacklist for Safari (macOS)
  pod 'SnapKit', '~> 5.0.0'
end

target 'uBlacklist for Safari Extension (iOS)' do
  platform :ios, '15.0'
  use_frameworks!

  # Pods for uBlacklist for Safari Extension (iOS)

end

target 'uBlacklist for Safari Extension (macOS)' do
  platform :osx, '10.14'
  use_frameworks!

  # Pods for uBlacklist for Safari Extension (macOS)

end
