target 'uBlacklist for Safari (iOS)' do
  platform :ios, '15.0'
  use_frameworks!

  # Pods for uBlacklist for Safari (iOS)
  pod 'SnapKit', '~> 5.0.0'
  pod 'RevenueCat'
  pod 'SVProgressHUD'
end

target 'uBlacklist for Safari (macOS)' do
  platform :osx, '10.14'
  use_frameworks!

  # Pods for uBlacklist for Safari (macOS)
  pod 'SnapKit', '~> 5.0.0'
end

target 'uBlacklist for Safari Extension (iOS)' do
  platform :ios, '15.0'
  use_frameworks!

  # Pods for uBlacklist for Safari Extension (iOS)

end

target 'uBlacklist for Safari Extension (macOS)' do
  platform :osx, '10.14'
  use_frameworks!

  # Pods for uBlacklist for Safari Extension (macOS)

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      if target.platform_name == :ios
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        end
      elsif target.platform_name == :osx
        target.build_configurations.each do |config|
          config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.14'
        end
      end
    end
  end
end
